apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-color
  namespace: argocd
spec:
  project: platform
  sources:
    # 1) Fuente del CHART (repo de la app)
    - repoURL: https://github.com/josefloressv/kcd_colombia_webapp_color.git
      targetRevision: main
      path: helm/webapp-color
      helm:
        valueFiles:
          - $values/clusters/prod/apps/webapp-color.values.yaml
    # 2) Fuente de los VALUES (repo de ambiente)
    - repoURL: https://github.com/josefloressv/kcd_colombia_env.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp-color
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true